# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\rgameengine.v1\"\x14\n\x04JSON\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"=\n\x05State\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0f\n\x07game_id\x18\x02 \x01(\t\x12\x12\n\nstep_index\x18\x03 \x01(\x03\"A\n\x06\x41\x63tion\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\"o\n\x0bStateUpdate\x12#\n\x05state\x18\x01 \x01(\x0b\x32\x14.gameengine.v1.State\x12\x14\n\x0creward_delta\x18\x02 \x01(\x01\x12\x13\n\x0bis_terminal\x18\x03 \x01(\x08\x12\x10\n\x08\x61\x63tor_id\x18\x04 \x01(\t\"k\n\x0fSessionMetadata\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fruleset_version\x18\x02 \x01(\t\x12\x12\n\nplayer_ids\x18\x03 \x03(\t\x12\x17\n\x0fstart_time_unix\x18\x04 \x01(\x03\x42@Z>github.com/game-engine/game-engine-core/api/proto/gen;enginepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/game-engine/game-engine-core/api/proto/gen;enginepb'
  _globals['_JSON']._serialized_start=31
  _globals['_JSON']._serialized_end=51
  _globals['_STATE']._serialized_start=53
  _globals['_STATE']._serialized_end=114
  _globals['_ACTION']._serialized_start=116
  _globals['_ACTION']._serialized_end=181
  _globals['_STATEUPDATE']._serialized_start=183
  _globals['_STATEUPDATE']._serialized_end=294
  _globals['_SESSIONMETADATA']._serialized_start=296
  _globals['_SESSIONMETADATA']._serialized_end=403
# @@protoc_insertion_point(module_scope)
