# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from game_engine_core.proto import common_pb2 as common__pb2
from game_engine_core.proto import gamesession_pb2 as gamesession__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gamesession_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameSessionStub(object):
    """GameSession drives a single live game: the client streams Actions and the
    server streams StateUpdates back in full-duplex mode.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Play = channel.stream_stream(
                '/gameengine.v1.GameSession/Play',
                request_serializer=common__pb2.Action.SerializeToString,
                response_deserializer=common__pb2.StateUpdate.FromString,
                _registered_method=True)
        self.GetReplay = channel.unary_stream(
                '/gameengine.v1.GameSession/GetReplay',
                request_serializer=gamesession__pb2.GetReplayRequest.SerializeToString,
                response_deserializer=gamesession__pb2.ReplayEntry.FromString,
                _registered_method=True)


class GameSessionServicer(object):
    """GameSession drives a single live game: the client streams Actions and the
    server streams StateUpdates back in full-duplex mode.
    """

    def Play(self, request_iterator, context):
        """Play is a bidirectional streaming RPC: the client sends Action messages
        and the server responds with StateUpdate messages until the game ends.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplay(self, request, context):
        """GetReplay streams all ReplayEntry records for a completed session,
        allowing clients to reconstruct the full game history from .glog data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameSessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Play': grpc.stream_stream_rpc_method_handler(
                    servicer.Play,
                    request_deserializer=common__pb2.Action.FromString,
                    response_serializer=common__pb2.StateUpdate.SerializeToString,
            ),
            'GetReplay': grpc.unary_stream_rpc_method_handler(
                    servicer.GetReplay,
                    request_deserializer=gamesession__pb2.GetReplayRequest.FromString,
                    response_serializer=gamesession__pb2.ReplayEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameengine.v1.GameSession', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameengine.v1.GameSession', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameSession(object):
    """GameSession drives a single live game: the client streams Actions and the
    server streams StateUpdates back in full-duplex mode.
    """

    @staticmethod
    def Play(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gameengine.v1.GameSession/Play',
            common__pb2.Action.SerializeToString,
            common__pb2.StateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gameengine.v1.GameSession/GetReplay',
            gamesession__pb2.GetReplayRequest.SerializeToString,
            gamesession__pb2.ReplayEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
