# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gamesession.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gamesession.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from game_engine_core.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gamesession.proto\x12\rgameengine.v1\x1a\x0c\x63ommon.proto\"T\n\x13StartSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x16\n\x0einitial_config\x18\x03 \x01(\x0c\"7\n\x11\x45ndSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"8\n\x12\x45ndSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"&\n\x10GetReplayRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x8c\x01\n\x0bReplayEntry\x12\x12\n\nstep_index\x18\x01 \x01(\x05\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63tion_taken\x18\x03 \x01(\x0c\x12\x16\n\x0estate_snapshot\x18\x04 \x01(\x0c\x12\x14\n\x0creward_delta\x18\x05 \x01(\x01\x12\x13\n\x0bis_terminal\x18\x06 \x01(\x08\x32\x98\x01\n\x0bGameSession\x12=\n\x04Play\x12\x15.gameengine.v1.Action\x1a\x1a.gameengine.v1.StateUpdate(\x01\x30\x01\x12J\n\tGetReplay\x12\x1f.gameengine.v1.GetReplayRequest\x1a\x1a.gameengine.v1.ReplayEntry0\x01\x42@Z>github.com/game-engine/game-engine-core/api/proto/gen;enginepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamesession_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/game-engine/game-engine-core/api/proto/gen;enginepb'
  _globals['_STARTSESSIONREQUEST']._serialized_start=50
  _globals['_STARTSESSIONREQUEST']._serialized_end=134
  _globals['_ENDSESSIONREQUEST']._serialized_start=136
  _globals['_ENDSESSIONREQUEST']._serialized_end=191
  _globals['_ENDSESSIONRESPONSE']._serialized_start=193
  _globals['_ENDSESSIONRESPONSE']._serialized_end=249
  _globals['_GETREPLAYREQUEST']._serialized_start=251
  _globals['_GETREPLAYREQUEST']._serialized_end=289
  _globals['_REPLAYENTRY']._serialized_start=292
  _globals['_REPLAYENTRY']._serialized_end=432
  _globals['_GAMESESSION']._serialized_start=435
  _globals['_GAMESESSION']._serialized_end=587
# @@protoc_insertion_point(module_scope)
