# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from game_engine_core.proto import matchmaking_pb2 as matchmaking__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in matchmaking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchmakingStub(object):
    """Matchmaking manages player lobbies and session creation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinLobby = channel.unary_stream(
                '/gameengine.v1.Matchmaking/JoinLobby',
                request_serializer=matchmaking__pb2.JoinRequest.SerializeToString,
                response_deserializer=matchmaking__pb2.LobbyStatusUpdate.FromString,
                _registered_method=True)
        self.CancelJoin = channel.unary_unary(
                '/gameengine.v1.Matchmaking/CancelJoin',
                request_serializer=matchmaking__pb2.JoinRequest.SerializeToString,
                response_deserializer=matchmaking__pb2.JoinResponse.FromString,
                _registered_method=True)


class MatchmakingServicer(object):
    """Matchmaking manages player lobbies and session creation.
    """

    def JoinLobby(self, request, context):
        """JoinLobby places the player in a lobby and streams status updates until the
        game starts or the request is cancelled.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJoin(self, request, context):
        """CancelJoin removes a waiting player from the lobby.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchmakingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinLobby': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinLobby,
                    request_deserializer=matchmaking__pb2.JoinRequest.FromString,
                    response_serializer=matchmaking__pb2.LobbyStatusUpdate.SerializeToString,
            ),
            'CancelJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJoin,
                    request_deserializer=matchmaking__pb2.JoinRequest.FromString,
                    response_serializer=matchmaking__pb2.JoinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameengine.v1.Matchmaking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameengine.v1.Matchmaking', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Matchmaking(object):
    """Matchmaking manages player lobbies and session creation.
    """

    @staticmethod
    def JoinLobby(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gameengine.v1.Matchmaking/JoinLobby',
            matchmaking__pb2.JoinRequest.SerializeToString,
            matchmaking__pb2.LobbyStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameengine.v1.Matchmaking/CancelJoin',
            matchmaking__pb2.JoinRequest.SerializeToString,
            matchmaking__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
