# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matchmaking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'matchmaking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11matchmaking.proto\x12\rgameengine.v1\"C\n\x0bJoinRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x11\n\tgame_type\x18\x02 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x03 \x01(\x0c\"F\n\x0cJoinResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nplayer_ids\x18\x03 \x03(\t\"U\n\x11LobbyStatusUpdate\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x15\n\rready_players\x18\x02 \x03(\t\x12\x15\n\rgame_starting\x18\x03 \x01(\x08\x32\xa1\x01\n\x0bMatchmaking\x12K\n\tJoinLobby\x12\x1a.gameengine.v1.JoinRequest\x1a .gameengine.v1.LobbyStatusUpdate0\x01\x12\x45\n\nCancelJoin\x12\x1a.gameengine.v1.JoinRequest\x1a\x1b.gameengine.v1.JoinResponseB@Z>github.com/game-engine/game-engine-core/api/proto/gen;enginepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matchmaking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/game-engine/game-engine-core/api/proto/gen;enginepb'
  _globals['_JOINREQUEST']._serialized_start=36
  _globals['_JOINREQUEST']._serialized_end=103
  _globals['_JOINRESPONSE']._serialized_start=105
  _globals['_JOINRESPONSE']._serialized_end=175
  _globals['_LOBBYSTATUSUPDATE']._serialized_start=177
  _globals['_LOBBYSTATUSUPDATE']._serialized_end=262
  _globals['_MATCHMAKING']._serialized_start=265
  _globals['_MATCHMAKING']._serialized_end=426
# @@protoc_insertion_point(module_scope)
