// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "gameengine.v1";

/** JSON is a wrapper for opaque JSON payloads transported as raw bytes. */
export interface JSON {
  data: Buffer;
}

/** State represents a snapshot of a game at a given step. */
export interface State {
  /** payload holds the opaque, game-specific encoded state. */
  payload: Buffer;
  /** game_id identifies the game type or session. */
  gameId: string;
  /** step_index is the monotonically increasing step counter. */
  stepIndex: number;
}

/** Action represents a single move performed by an actor. */
export interface Action {
  /** actor_id identifies the player or AI that produced this action. */
  actorId: string;
  /** payload holds the opaque, game-specific encoded action. */
  payload: Buffer;
  /** timestamp_ms is the wall-clock time when the action was recorded (Unix ms). */
  timestampMs: number;
}

/** StateUpdate is sent from the server to a player after each transition. */
export interface StateUpdate {
  /** state is the new game state after the action was applied. */
  state: State | undefined;
  /** reward_delta is the immediate reward (or score change) for the actor. */
  rewardDelta: number;
  /** is_terminal flags whether this update ends the game. */
  isTerminal: boolean;
  /** actor_id identifies which player this update is addressed to. */
  actorId: string;
}

/** SessionMetadata records context for a single game session. */
export interface SessionMetadata {
  /** session_id is the unique identifier for this session. */
  sessionId: string;
  /** ruleset_version identifies the game rules in use. */
  rulesetVersion: string;
  /** player_ids lists all participating player identifiers. */
  playerIds: string[];
  /** start_time_unix is the session start time as a Unix timestamp (seconds). */
  startTimeUnix: number;
}

function createBaseJSON(): JSON {
  return { data: Buffer.alloc(0) };
}

export const JSON: MessageFns<JSON> = {
  encode(
    message: JSON,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JSON {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJSON();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JSON {
    return {
      data: isSet(object.data)
        ? Buffer.from(bytesFromBase64(object.data))
        : Buffer.alloc(0),
    };
  },

  toJSON(message: JSON): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JSON>, I>>(base?: I): JSON {
    return JSON.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JSON>, I>>(object: I): JSON {
    const message = createBaseJSON();
    message.data = object.data ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseState(): State {
  return { payload: Buffer.alloc(0), gameId: "", stepIndex: 0 };
}

export const State: MessageFns<State> = {
  encode(
    message: State,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    if (message.gameId !== "") {
      writer.uint32(18).string(message.gameId);
    }
    if (message.stepIndex !== 0) {
      writer.uint32(24).int64(message.stepIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): State {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.gameId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.stepIndex = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): State {
    return {
      payload: isSet(object.payload)
        ? Buffer.from(bytesFromBase64(object.payload))
        : Buffer.alloc(0),
      gameId: isSet(object.gameId)
        ? globalThis.String(object.gameId)
        : isSet(object.game_id)
          ? globalThis.String(object.game_id)
          : "",
      stepIndex: isSet(object.stepIndex)
        ? globalThis.Number(object.stepIndex)
        : isSet(object.step_index)
          ? globalThis.Number(object.step_index)
          : 0,
    };
  },

  toJSON(message: State): unknown {
    const obj: any = {};
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.gameId !== "") {
      obj.gameId = message.gameId;
    }
    if (message.stepIndex !== 0) {
      obj.stepIndex = Math.round(message.stepIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<State>, I>>(base?: I): State {
    return State.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<State>, I>>(object: I): State {
    const message = createBaseState();
    message.payload = object.payload ?? Buffer.alloc(0);
    message.gameId = object.gameId ?? "";
    message.stepIndex = object.stepIndex ?? 0;
    return message;
  },
};

function createBaseAction(): Action {
  return { actorId: "", payload: Buffer.alloc(0), timestampMs: 0 };
}

export const Action: MessageFns<Action> = {
  encode(
    message: Action,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.actorId !== "") {
      writer.uint32(10).string(message.actorId);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(24).int64(message.timestampMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Action {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.actorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Action {
    return {
      actorId: isSet(object.actorId)
        ? globalThis.String(object.actorId)
        : isSet(object.actor_id)
          ? globalThis.String(object.actor_id)
          : "",
      payload: isSet(object.payload)
        ? Buffer.from(bytesFromBase64(object.payload))
        : Buffer.alloc(0),
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
          ? globalThis.Number(object.timestamp_ms)
          : 0,
    };
  },

  toJSON(message: Action): unknown {
    const obj: any = {};
    if (message.actorId !== "") {
      obj.actorId = message.actorId;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Action>, I>>(base?: I): Action {
    return Action.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Action>, I>>(object: I): Action {
    const message = createBaseAction();
    message.actorId = object.actorId ?? "";
    message.payload = object.payload ?? Buffer.alloc(0);
    message.timestampMs = object.timestampMs ?? 0;
    return message;
  },
};

function createBaseStateUpdate(): StateUpdate {
  return { state: undefined, rewardDelta: 0, isTerminal: false, actorId: "" };
}

export const StateUpdate: MessageFns<StateUpdate> = {
  encode(
    message: StateUpdate,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.state !== undefined) {
      State.encode(message.state, writer.uint32(10).fork()).join();
    }
    if (message.rewardDelta !== 0) {
      writer.uint32(17).double(message.rewardDelta);
    }
    if (message.isTerminal !== false) {
      writer.uint32(24).bool(message.isTerminal);
    }
    if (message.actorId !== "") {
      writer.uint32(34).string(message.actorId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateUpdate {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = State.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.rewardDelta = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isTerminal = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.actorId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateUpdate {
    return {
      state: isSet(object.state) ? State.fromJSON(object.state) : undefined,
      rewardDelta: isSet(object.rewardDelta)
        ? globalThis.Number(object.rewardDelta)
        : isSet(object.reward_delta)
          ? globalThis.Number(object.reward_delta)
          : 0,
      isTerminal: isSet(object.isTerminal)
        ? globalThis.Boolean(object.isTerminal)
        : isSet(object.is_terminal)
          ? globalThis.Boolean(object.is_terminal)
          : false,
      actorId: isSet(object.actorId)
        ? globalThis.String(object.actorId)
        : isSet(object.actor_id)
          ? globalThis.String(object.actor_id)
          : "",
    };
  },

  toJSON(message: StateUpdate): unknown {
    const obj: any = {};
    if (message.state !== undefined) {
      obj.state = State.toJSON(message.state);
    }
    if (message.rewardDelta !== 0) {
      obj.rewardDelta = message.rewardDelta;
    }
    if (message.isTerminal !== false) {
      obj.isTerminal = message.isTerminal;
    }
    if (message.actorId !== "") {
      obj.actorId = message.actorId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateUpdate>, I>>(base?: I): StateUpdate {
    return StateUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateUpdate>, I>>(
    object: I,
  ): StateUpdate {
    const message = createBaseStateUpdate();
    message.state =
      object.state !== undefined && object.state !== null
        ? State.fromPartial(object.state)
        : undefined;
    message.rewardDelta = object.rewardDelta ?? 0;
    message.isTerminal = object.isTerminal ?? false;
    message.actorId = object.actorId ?? "";
    return message;
  },
};

function createBaseSessionMetadata(): SessionMetadata {
  return { sessionId: "", rulesetVersion: "", playerIds: [], startTimeUnix: 0 };
}

export const SessionMetadata: MessageFns<SessionMetadata> = {
  encode(
    message: SessionMetadata,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.rulesetVersion !== "") {
      writer.uint32(18).string(message.rulesetVersion);
    }
    for (const v of message.playerIds) {
      writer.uint32(26).string(v!);
    }
    if (message.startTimeUnix !== 0) {
      writer.uint32(32).int64(message.startTimeUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionMetadata {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rulesetVersion = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.playerIds.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.startTimeUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionMetadata {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
          ? globalThis.String(object.session_id)
          : "",
      rulesetVersion: isSet(object.rulesetVersion)
        ? globalThis.String(object.rulesetVersion)
        : isSet(object.ruleset_version)
          ? globalThis.String(object.ruleset_version)
          : "",
      playerIds: globalThis.Array.isArray(object?.playerIds)
        ? object.playerIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.player_ids)
          ? object.player_ids.map((e: any) => globalThis.String(e))
          : [],
      startTimeUnix: isSet(object.startTimeUnix)
        ? globalThis.Number(object.startTimeUnix)
        : isSet(object.start_time_unix)
          ? globalThis.Number(object.start_time_unix)
          : 0,
    };
  },

  toJSON(message: SessionMetadata): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.rulesetVersion !== "") {
      obj.rulesetVersion = message.rulesetVersion;
    }
    if (message.playerIds?.length) {
      obj.playerIds = message.playerIds;
    }
    if (message.startTimeUnix !== 0) {
      obj.startTimeUnix = Math.round(message.startTimeUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionMetadata>, I>>(
    base?: I,
  ): SessionMetadata {
    return SessionMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionMetadata>, I>>(
    object: I,
  ): SessionMetadata {
    const message = createBaseSessionMetadata();
    message.sessionId = object.sessionId ?? "";
    message.rulesetVersion = object.rulesetVersion ?? "";
    message.playerIds = object.playerIds?.map((e) => e) || [];
    message.startTimeUnix = object.startTimeUnix ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
