// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: gamesession.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "gameengine.v1";

/** StartSessionRequest initiates a new game session stream. */
export interface StartSessionRequest {
  /** session_id is the pre-assigned identifier for this session. */
  sessionId: string;
  /** player_id identifies the player connecting to the session. */
  playerId: string;
  /** initial_config carries optional game-specific configuration bytes. */
  initialConfig: Uint8Array;
}

/** EndSessionRequest asks the server to terminate a session. */
export interface EndSessionRequest {
  /** session_id identifies the session to end. */
  sessionId: string;
  /** reason is a human-readable explanation for ending the session. */
  reason: string;
}

/** EndSessionResponse is returned when a session has been terminated. */
export interface EndSessionResponse {
  /** session_id echoes the terminated session's identifier. */
  sessionId: string;
  /** reason echoes the reason supplied in the request. */
  reason: string;
}

/** GetReplayRequest asks the server to stream the replay log for a session. */
export interface GetReplayRequest {
  /** session_id identifies the completed session whose replay is requested. */
  sessionId: string;
}

/** ReplayEntry mirrors one row of the .glog schema. */
export interface ReplayEntry {
  /** step_index is the zero-based ordinal of this transition. */
  stepIndex: number;
  /** actor_id identifies the player or AI that performed the action. */
  actorId: string;
  /** action_taken is the opaque, game-specific encoded action. */
  actionTaken: Uint8Array;
  /** state_snapshot is the encoded game state immediately after the action. */
  stateSnapshot: Uint8Array;
  /** reward_delta is the immediate reward associated with this transition. */
  rewardDelta: number;
  /** is_terminal is true if this entry represents the final step of the game. */
  isTerminal: boolean;
}

function createBaseStartSessionRequest(): StartSessionRequest {
  return { sessionId: "", playerId: "", initialConfig: new Uint8Array(0) };
}

export const StartSessionRequest = {
  encode(message: StartSessionRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.playerId !== "") {
      writer.uint32(18).string(message.playerId);
    }
    if (message.initialConfig.length !== 0) {
      writer.uint32(26).bytes(message.initialConfig);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StartSessionRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.playerId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.initialConfig = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartSessionRequest {
    return {
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      playerId: isSet(object.playerId) ? globalThis.String(object.playerId) : "",
      initialConfig: isSet(object.initialConfig) ? bytesFromBase64(object.initialConfig) : new Uint8Array(0),
    };
  },

  toJSON(message: StartSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.playerId !== "") {
      obj.playerId = message.playerId;
    }
    if (message.initialConfig.length !== 0) {
      obj.initialConfig = base64FromBytes(message.initialConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StartSessionRequest>, I>>(base?: I): StartSessionRequest {
    return StartSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartSessionRequest>, I>>(object: I): StartSessionRequest {
    const message = createBaseStartSessionRequest();
    message.sessionId = object.sessionId ?? "";
    message.playerId = object.playerId ?? "";
    message.initialConfig = object.initialConfig ?? new Uint8Array(0);
    return message;
  },
};

function createBaseEndSessionRequest(): EndSessionRequest {
  return { sessionId: "", reason: "" };
}

export const EndSessionRequest = {
  encode(message: EndSessionRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EndSessionRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEndSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EndSessionRequest {
    return {
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: EndSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EndSessionRequest>, I>>(base?: I): EndSessionRequest {
    return EndSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EndSessionRequest>, I>>(object: I): EndSessionRequest {
    const message = createBaseEndSessionRequest();
    message.sessionId = object.sessionId ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseEndSessionResponse(): EndSessionResponse {
  return { sessionId: "", reason: "" };
}

export const EndSessionResponse = {
  encode(message: EndSessionResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EndSessionResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEndSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EndSessionResponse {
    return {
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: EndSessionResponse): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EndSessionResponse>, I>>(base?: I): EndSessionResponse {
    return EndSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EndSessionResponse>, I>>(object: I): EndSessionResponse {
    const message = createBaseEndSessionResponse();
    message.sessionId = object.sessionId ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseGetReplayRequest(): GetReplayRequest {
  return { sessionId: "" };
}

export const GetReplayRequest = {
  encode(message: GetReplayRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetReplayRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetReplayRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetReplayRequest {
    return { sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "" };
  },

  toJSON(message: GetReplayRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetReplayRequest>, I>>(base?: I): GetReplayRequest {
    return GetReplayRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetReplayRequest>, I>>(object: I): GetReplayRequest {
    const message = createBaseGetReplayRequest();
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseReplayEntry(): ReplayEntry {
  return {
    stepIndex: 0,
    actorId: "",
    actionTaken: new Uint8Array(0),
    stateSnapshot: new Uint8Array(0),
    rewardDelta: 0,
    isTerminal: false,
  };
}

export const ReplayEntry = {
  encode(message: ReplayEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.stepIndex !== 0) {
      writer.uint32(8).int32(message.stepIndex);
    }
    if (message.actorId !== "") {
      writer.uint32(18).string(message.actorId);
    }
    if (message.actionTaken.length !== 0) {
      writer.uint32(26).bytes(message.actionTaken);
    }
    if (message.stateSnapshot.length !== 0) {
      writer.uint32(34).bytes(message.stateSnapshot);
    }
    if (message.rewardDelta !== 0) {
      writer.uint32(41).double(message.rewardDelta);
    }
    if (message.isTerminal !== false) {
      writer.uint32(48).bool(message.isTerminal);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReplayEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplayEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.stepIndex = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.actorId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.actionTaken = reader.bytes();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.stateSnapshot = reader.bytes();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.rewardDelta = reader.double();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.isTerminal = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReplayEntry {
    return {
      stepIndex: isSet(object.stepIndex) ? globalThis.Number(object.stepIndex) : 0,
      actorId: isSet(object.actorId) ? globalThis.String(object.actorId) : "",
      actionTaken: isSet(object.actionTaken) ? bytesFromBase64(object.actionTaken) : new Uint8Array(0),
      stateSnapshot: isSet(object.stateSnapshot) ? bytesFromBase64(object.stateSnapshot) : new Uint8Array(0),
      rewardDelta: isSet(object.rewardDelta) ? globalThis.Number(object.rewardDelta) : 0,
      isTerminal: isSet(object.isTerminal) ? globalThis.Boolean(object.isTerminal) : false,
    };
  },

  toJSON(message: ReplayEntry): unknown {
    const obj: any = {};
    if (message.stepIndex !== 0) {
      obj.stepIndex = Math.round(message.stepIndex);
    }
    if (message.actorId !== "") {
      obj.actorId = message.actorId;
    }
    if (message.actionTaken.length !== 0) {
      obj.actionTaken = base64FromBytes(message.actionTaken);
    }
    if (message.stateSnapshot.length !== 0) {
      obj.stateSnapshot = base64FromBytes(message.stateSnapshot);
    }
    if (message.rewardDelta !== 0) {
      obj.rewardDelta = message.rewardDelta;
    }
    if (message.isTerminal !== false) {
      obj.isTerminal = message.isTerminal;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReplayEntry>, I>>(base?: I): ReplayEntry {
    return ReplayEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplayEntry>, I>>(object: I): ReplayEntry {
    const message = createBaseReplayEntry();
    message.stepIndex = object.stepIndex ?? 0;
    message.actorId = object.actorId ?? "";
    message.actionTaken = object.actionTaken ?? new Uint8Array(0);
    message.stateSnapshot = object.stateSnapshot ?? new Uint8Array(0);
    message.rewardDelta = object.rewardDelta ?? 0;
    message.isTerminal = object.isTerminal ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
