// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: matchmaking.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "gameengine.v1";

/** JoinRequest is sent by a player wishing to enter a lobby. */
export interface JoinRequest {
  /** player_id uniquely identifies the requesting player. */
  playerId: string;
  /** game_type specifies which game the player wants to play. */
  gameType: string;
  /** config carries optional, game-specific configuration bytes. */
  config: Uint8Array;
}

/** JoinResponse is returned when a lobby action (e.g. cancel) completes. */
export interface JoinResponse {
  /** session_id is the lobby or session identifier (may be empty if not yet assigned). */
  sessionId: string;
  /** status is a human-readable status string (e.g. "waiting", "cancelled"). */
  status: string;
  /** player_ids lists all players currently in the session or lobby. */
  playerIds: string[];
}

/** LobbyStatusUpdate is streamed to players while they wait in a lobby. */
export interface LobbyStatusUpdate {
  /** session_id identifies the lobby. */
  sessionId: string;
  /** ready_players lists the player IDs that have confirmed readiness. */
  readyPlayers: string[];
  /** game_starting is true on the final update, signalling the game is about to begin. */
  gameStarting: boolean;
}

function createBaseJoinRequest(): JoinRequest {
  return { playerId: "", gameType: "", config: new Uint8Array(0) };
}

export const JoinRequest = {
  encode(message: JoinRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.playerId !== "") {
      writer.uint32(10).string(message.playerId);
    }
    if (message.gameType !== "") {
      writer.uint32(18).string(message.gameType);
    }
    if (message.config.length !== 0) {
      writer.uint32(26).bytes(message.config);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): JoinRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.playerId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.gameType = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.config = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinRequest {
    return {
      playerId: isSet(object.playerId) ? globalThis.String(object.playerId) : "",
      gameType: isSet(object.gameType) ? globalThis.String(object.gameType) : "",
      config: isSet(object.config) ? bytesFromBase64(object.config) : new Uint8Array(0),
    };
  },

  toJSON(message: JoinRequest): unknown {
    const obj: any = {};
    if (message.playerId !== "") {
      obj.playerId = message.playerId;
    }
    if (message.gameType !== "") {
      obj.gameType = message.gameType;
    }
    if (message.config.length !== 0) {
      obj.config = base64FromBytes(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JoinRequest>, I>>(base?: I): JoinRequest {
    return JoinRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JoinRequest>, I>>(object: I): JoinRequest {
    const message = createBaseJoinRequest();
    message.playerId = object.playerId ?? "";
    message.gameType = object.gameType ?? "";
    message.config = object.config ?? new Uint8Array(0);
    return message;
  },
};

function createBaseJoinResponse(): JoinResponse {
  return { sessionId: "", status: "", playerIds: [] };
}

export const JoinResponse = {
  encode(message: JoinResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    for (const v of message.playerIds) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): JoinResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJoinResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.playerIds.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JoinResponse {
    return {
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      playerIds: globalThis.Array.isArray(object?.playerIds)
        ? object.playerIds.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: JoinResponse): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.playerIds?.length) {
      obj.playerIds = message.playerIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JoinResponse>, I>>(base?: I): JoinResponse {
    return JoinResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JoinResponse>, I>>(object: I): JoinResponse {
    const message = createBaseJoinResponse();
    message.sessionId = object.sessionId ?? "";
    message.status = object.status ?? "";
    message.playerIds = object.playerIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseLobbyStatusUpdate(): LobbyStatusUpdate {
  return { sessionId: "", readyPlayers: [], gameStarting: false };
}

export const LobbyStatusUpdate = {
  encode(message: LobbyStatusUpdate, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    for (const v of message.readyPlayers) {
      writer.uint32(18).string(v!);
    }
    if (message.gameStarting !== false) {
      writer.uint32(24).bool(message.gameStarting);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LobbyStatusUpdate {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLobbyStatusUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.readyPlayers.push(reader.string());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.gameStarting = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LobbyStatusUpdate {
    return {
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      readyPlayers: globalThis.Array.isArray(object?.readyPlayers)
        ? object.readyPlayers.map((e: any) => globalThis.String(e))
        : [],
      gameStarting: isSet(object.gameStarting) ? globalThis.Boolean(object.gameStarting) : false,
    };
  },

  toJSON(message: LobbyStatusUpdate): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.readyPlayers?.length) {
      obj.readyPlayers = message.readyPlayers;
    }
    if (message.gameStarting !== false) {
      obj.gameStarting = message.gameStarting;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LobbyStatusUpdate>, I>>(base?: I): LobbyStatusUpdate {
    return LobbyStatusUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LobbyStatusUpdate>, I>>(object: I): LobbyStatusUpdate {
    const message = createBaseLobbyStatusUpdate();
    message.sessionId = object.sessionId ?? "";
    message.readyPlayers = object.readyPlayers?.map((e) => e) || [];
    message.gameStarting = object.gameStarting ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
